Add Dockerfile, requirements.txt, summary_demo.py
ainize-team/xangle-summary-demo pull request #1
Opened 2021-08-25 01:40 UTC by 589hero

1. docker build -t <docker image name> .
2. docker run -it -p 8051:8051 <docker image name>
3. http://localhost:8051 접속

2021-08-25 03:38 UTC, byeongal commented on requirements.txt
> +torch==1.6.0
torch 랑 transformer는 여기서 필요 없을 것 같습니다.

2021-08-25 03:38 UTC, byeongal commented on requirements.txt
> +watchdog
version

2021-08-25 03:46 UTC, pellto-comcom requested changes

2021-08-25 03:46 UTC, pellto-comcom commented on summary_demo.py
> +sub_categories = {
상수로 사용하는 것으로 보이네요. 전역 상수 네이밍을 대문자로 해주시는 것이 좋아보입니다.

2021-08-25 03:46 UTC, pellto-comcom commented on summary_demo.py
> +        # res = requests.post(f'http://localhost/api/{category}/{sub_category}', data=json.dumps(data), headers={"Content-Type": "application/json"})
필요없어 보이는 코드 주석 삭제

2021-08-25 03:46 UTC, pellto-comcom commented on summary_demo.py
> +        res = {
더미데이터가 들어가 있는 부분을 '// @TODO' 를 적어주세요.

2021-08-25 03:46 UTC, pellto-comcom commented on summary_demo.py
> +        Categories.new_listing,
확장되어야 하는 부분도 TODO 적어주세요.

2021-08-26 02:37 UTC, byeongal approved these changes
LGTM!

2021-08-26 02:38 UTC, pellto-comcom approved these changes
LGTM!

2021-08-26 09:19 UTC, byeongal requested changes

2021-08-26 09:19 UTC, byeongal commented on summary_demo.py
> +        model_url = 'https://train-mw86iwjxfypsj60gvh84-gpt2-train-teachable-ainize.endpoint.dev.ainize.ai/predictions/xangle-summary'
model 을 사용자에게 입력 받으면 좋을 것 같습니다.

2021-08-26 09:19 UTC, byeongal commented on summary_demo.py
> +        summary += f'{i+1}. {sub_category}' + '\n' + f'{output}' + '\n\n'
이 부분 xangle 글이랑 똑같이 나오게 해주세요.

2021-08-26 09:19 UTC, byeongal commented on summary_demo.py
> +    'New Partnership': [
순서 확인 부탁 드립니다.

2021-08-26 09:24 UTC, pellto-comcom approved these changes
LGTM

2021-08-27 05:27 UTC, byeongal approved these changes
LGTM!

2021-08-27 05:37 UTC, merged